### ISSUE TITLE
🐛 Active tab panel inaccurate when going back many times

### ISSUE THREAD

**Issue by code-arman** [hack4impact-uiuc/brink#74]
**To Reproduce**

1. Go to '/home/faq'
2. Click on the Ballot tab
3. Press back button
4. See that the FAQ content renders under the Ballot tab

**Expected behavior**
The active tab should be VoterFAQ
**Screenshots**
![Screen Shot 2022-03-27 at 2 29 21 AM](https://user-images.githubusercontent.com/46976119/160271451-2dd1d83c-4035-46ca-b97e-f1780954c0e1.png)

**Comment by amit-sawhney** [comment]
Resolved itself
