### ISSUE TITLE
Add picture to photos and update README.md

### ISSUE THREAD

**Issue by amit-sawhney** [hack4impact-uiuc/brink#9]
**Type**: infra
**FOF**: 1

## Description

Checkout the `add-readme-photos` branch and add a picture of yourself in the `photos/` directory with the filename being of the form: firstname-lastname.jpg`. Update the README to include yourself in table: 
- Product managers, Tech Leads, and Designers in first now
- Developers in second row
- Please update the link to be your LinkedIn or personal website

## Todo

- [x] Amit
- [x] Ayan
- [x] Bryan
- [x] Jocelyn
- [x] Arman
- [x] Sue
- [x] Eric

**Comment by maazshakeel** [comment]
I'll work on this!
